name: agent_purple
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - openai==1.72.0
      - autogen==0.8.5
      - gradio==5.24.0
      - requests==2.32.3
      - pyyaml==6.0.1
      - stix2==3.0.1
      - taxii2-client==2.3.0
      - python-dotenv==1.1.0
      - pytest==8.3.5
      - black==25.1.0
      - flake8==7.2.0
      - mypy==1.15.1
      - paramiko==2.8.1
      - pygit2==1.17.0
      - cryptography==43.0.0
